### ISSUE TITLE
log spam

### ISSUE THREAD

**Issue by Moonyol** [kurrycat2004/MPKMod_2#28]
log being spammed with this, i cant reproduce it
[17:49:38] [mpkmod GUI Tick Thread/INFO]: InfoMap: IllegalAccessException while trying to access method getFacing from io.github.kurrycat.mpkmod.compatibility.MCClasses.Player
[17:49:38] [mpkmod GUI Tick Thread/INFO]: 	at io.github.kurrycat.mpkmod.util.Debug.stacktrace(Debug.java:7)
	at io.github.kurrycat.mpkmod.gui.infovars.InfoString.getObj(InfoString.java:69)
	at io.github.kurrycat.mpkmod.gui.infovars.InfoVar.getObj(InfoVar.java:42)
	at io.github.kurrycat.mpkmod.gui.infovars.InfoString$Provider.get(InfoString.java:269)
	at io.github.kurrycat.mpkmod.gui.infovars.InfoString.get(InfoString.java:209)
	at io.github.kurrycat.mpkmod.gui.components.InfoLabel.tick(InfoLabel.java:64)
	at io.github.kurrycat.mpkmod.gui.TickThread$Tickable.runTick(TickThread.java:45)
	at io.github.kurrycat.mpkmod.gui.TickThread.run(TickThread.java:34)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by CodeKid0** [comment]
More info? Game version, mod loader

**Comment by Moonyol** [comment]
minecraft 1.20.1, fabric 0.14.21, mpkmod-2.0.0-pre.9-fabric-1.20.jar

**Comment by CodeKid0** [comment]
Does it still happen? If so, please delete your configuration files
